# Generated by Django 4.1.7 on 2025-05-20 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Program_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(default='Информация', max_length=255, verbose_name='Впишите нужную фразу')),
                ('a', models.CharField(default='Обо мне', max_length=255, verbose_name='Значение')),
                ('result', models.CharField(default='Результат', max_length=255, verbose_name='Результат')),
                ('current_date', models.DateTimeField(auto_now=True, verbose_name='Дата изменения(save)')),
            ],
            options={
                'verbose_name': ' Таблица результатов',
                'verbose_name_plural': 'Таблицы результатов',
                'ordering': ('-pk',),
            },
        ),
    ]
